### ISSUE TITLE
ClosestDefenderAggregate API returning 400 Bad Request

### ISSUE THREAD

**Issue by sstevesun** [toddwschneider/nba-shots-db#12] opened 2020-11-30 13:25 UTC
Hello, I'm having a problem with the setup command, bundle exec rake db:setup, where this triggers an unexpected token error.  I believe this is the relevant portion of the trace:

...
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke db:load_config
** Execute db:abort_if_pending_migrations
rake aborted!
JSON::ParserError: 765: unexpected token at ''
C:/Ruby25-x64/lib/ruby/2.5.0/json/common.rb:156:in `parse'
C:/Ruby25-x64/lib/ruby/2.5.0/json/common.rb:156:in `parse'
C:/Users/sstev/nba-shots-db/app/lib/nba_stats_client.rb:163:in `get'
C:/Users/sstev/nba-shots-db/app/lib/nba_stats_client.rb:21:in `all_players'
C:/Users/sstev/nba-shots-db/app/models/player.rb:77:in `import_all'
C:/Users/sstev/nba-shots-db/db/seeds.rb:1:in `<top (required)>'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `block in load'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
...

It seems there are rather a lot of ways to get this type of JSON error, so in the end I wasn't able to solve it by searching for it... I appreciate any insight you can give into the problem.

**Comment by toddwschneider** [comment] 2020-12-02 21:08
Hi @sstevesun thanks for reporting. Confirmed I'm getting this error too, it is likely due to changes on the NBA API side. I will investigate more when I have a chance

**Comment by toddwschneider** [comment] 2020-12-05 15:06
Hi @sstevesun I believe this is fixed by #13. It works for me again, but lmk if you still have issues. Thanks

**Comment by sstevesun** [comment] 2020-12-06 13:14
> 
> 
> Hi @sstevesun I believe this is fixed by #13. It works for me again, but lmk if you still have issues. Thanks

Thanks for your help.  This does make the setup command work, but some types of subsequent data collection commands fail with 400 Bad Request errors e.g.:

[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job Shot.create_all_by_without_delay (id=49) RUNNING
[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job Shot.create_all_by_without_delay (id=49) COMPLETED after 1.2571
[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job Shot.create_all_by_without_delay (id=50) RUNNING
[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job Shot.create_all_by_without_delay (id=50) COMPLETED after 1.2833
[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job Shot.create_all_by_without_delay (id=51) RUNNING
[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job Shot.create_all_by_without_delay (id=51) COMPLETED after 1.5120
[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job Shot.create_all_by_without_delay (id=52) RUNNING
[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job Shot.create_all_by_without_delay (id=52) COMPLETED after 1.5754
[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job ClosestDefenderAggregate.create_all_by_without_delay (id=53) RUNNING
[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job ClosestDefenderAggregate.create_all_by_without_delay (id=53) FAILED (0 prior attempts) with RestClient::BadRequest: 400 Bad Request
[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job ClosestDefenderAggregate.create_all_by_without_delay (id=54) RUNNING
[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job ClosestDefenderAggregate.create_all_by_without_delay (id=54) FAILED (0 prior attempts) with RestClient::BadRequest: 400 Bad Request
[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job ClosestDefenderAggregate.create_all_by_without_delay (id=55) RUNNING
[Worker(host:DESKTOP-CNU30BJ pid:1296)] Job ClosestDefenderAggregate.create_all_by_without_delay (id=55) FAILED (0 prior attempts) with RestClient::BadRequest: 400 Bad Request

or alternatively a timeout:

[Worker(host:DESKTOP-CNU30BJ pid:16628)] Job ClosestDefenderAggregate.create_all_by_without_delay (id=393) RUNNING
[Worker(host:DESKTOP-CNU30BJ pid:16628)] Job ClosestDefenderAggregate.create_all_by_without_delay (id=393) FAILED (0 prior attempts) with RestClient::Exceptions::ReadTimeout: Timed out reading data from server

... wondering if this is a misconfiguration on my part but since it didn't trigger for the Shot commands, I guessed it might be related?

**Comment by toddwschneider** [comment] 2020-12-07 12:57
@sstevesun you're right, it looks like the `ClosestDefenderAggregate` requests are still broken. I've renamed this issue and reopened it, will take a look when I can

**Comment by toddwschneider** [comment] 2020-12-12 14:00
Hi @sstevesun, I looked around a bit more and unfortunately it seems like the `ClosestDefenderAggregate` data is no longer supported by the NBA API

I just merged https://github.com/toddwschneider/nba-shots-db/pull/14 to remove that data from the database initialization task. Can you confirm that the setup process works for you now? It should only populate the `shots` table, not the `closest_defender_aggregates` table. Thanks

**Comment by sstevesun** [comment] 2020-12-14 00:32
Yes, setup appears to work fine--it still references the closest_defender_aggregates table in the setup command, but the batch job itself does not attempt to run those so there doesn't appear to be any impact from that.

**Comment by toddwschneider** [comment] 2020-12-14 01:29
Ok thanks. I'm closing this issue, but feel free to reopen if you encounter more problems

**Closed as completed by toddwschneider** 2020-12-14 01:29 UTC
